/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { VetRegistry } from "./VetRegistry";
export * as factories from "./factories";
export { VetRegistry__factory } from "./factories/VetRegistry__factory";
