/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as vetRegistrySol from "./VetRegistry.sol";
export type { vetRegistrySol };
import type * as test from "./test";
export type { test };
export * as factories from "./factories";
export type { MockERC20 } from "./test/MockERC20";
export { MockERC20__factory } from "./factories/test/MockERC20__factory";
export type { IERC20 } from "./VetRegistry.sol/IERC20";
export { IERC20__factory } from "./factories/VetRegistry.sol/IERC20__factory";
export type { VetRegistry } from "./VetRegistry.sol/VetRegistry";
export { VetRegistry__factory } from "./factories/VetRegistry.sol/VetRegistry__factory";
