/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export declare namespace VetRegistry {
  export type MedicalRecordStruct = {
    name: string;
    age: BigNumberish;
    animalType: BigNumberish;
    caretakerName: string;
    caretakerPhone: string;
  };

  export type MedicalRecordStructOutput = [
    name: string,
    age: bigint,
    animalType: bigint,
    caretakerName: string,
    caretakerPhone: string
  ] & {
    name: string;
    age: bigint;
    animalType: bigint;
    caretakerName: string;
    caretakerPhone: string;
  };
}

export interface VetRegistryInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "getMedicalRecord"
      | "getPetCount"
      | "registerPet"
      | "scheduleAppointment"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic: "MedicalAppointmentCreated" | "MedicalRecordCreated"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "getMedicalRecord",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getPetCount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "registerPet",
    values: [string, BigNumberish, BigNumberish, string, string]
  ): string;
  encodeFunctionData(
    functionFragment: "scheduleAppointment",
    values: [BigNumberish, BigNumberish, string, BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "getMedicalRecord",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getPetCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "registerPet",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "scheduleAppointment",
    data: BytesLike
  ): Result;
}

export namespace MedicalAppointmentCreatedEvent {
  export type InputTuple = [
    id: BigNumberish,
    petId: BigNumberish,
    date: BigNumberish,
    time: string,
    appointmentValue: BigNumberish
  ];
  export type OutputTuple = [
    id: bigint,
    petId: bigint,
    date: bigint,
    time: string,
    appointmentValue: bigint
  ];
  export interface OutputObject {
    id: bigint;
    petId: bigint;
    date: bigint;
    time: string;
    appointmentValue: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace MedicalRecordCreatedEvent {
  export type InputTuple = [
    id: BigNumberish,
    name: string,
    age: BigNumberish,
    animalType: BigNumberish,
    caretakerName: string,
    caretakerPhone: string
  ];
  export type OutputTuple = [
    id: bigint,
    name: string,
    age: bigint,
    animalType: bigint,
    caretakerName: string,
    caretakerPhone: string
  ];
  export interface OutputObject {
    id: bigint;
    name: string;
    age: bigint;
    animalType: bigint;
    caretakerName: string;
    caretakerPhone: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface VetRegistry extends BaseContract {
  connect(runner?: ContractRunner | null): VetRegistry;
  waitForDeployment(): Promise<this>;

  interface: VetRegistryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  getMedicalRecord: TypedContractMethod<
    [id: BigNumberish],
    [VetRegistry.MedicalRecordStructOutput],
    "view"
  >;

  getPetCount: TypedContractMethod<[], [bigint], "view">;

  registerPet: TypedContractMethod<
    [
      name: string,
      age: BigNumberish,
      animalType: BigNumberish,
      caretakerName: string,
      caretakerPhone: string
    ],
    [bigint],
    "nonpayable"
  >;

  scheduleAppointment: TypedContractMethod<
    [
      petId: BigNumberish,
      date: BigNumberish,
      time: string,
      appointmentValue: BigNumberish
    ],
    [bigint],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "getMedicalRecord"
  ): TypedContractMethod<
    [id: BigNumberish],
    [VetRegistry.MedicalRecordStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getPetCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "registerPet"
  ): TypedContractMethod<
    [
      name: string,
      age: BigNumberish,
      animalType: BigNumberish,
      caretakerName: string,
      caretakerPhone: string
    ],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "scheduleAppointment"
  ): TypedContractMethod<
    [
      petId: BigNumberish,
      date: BigNumberish,
      time: string,
      appointmentValue: BigNumberish
    ],
    [bigint],
    "nonpayable"
  >;

  getEvent(
    key: "MedicalAppointmentCreated"
  ): TypedContractEvent<
    MedicalAppointmentCreatedEvent.InputTuple,
    MedicalAppointmentCreatedEvent.OutputTuple,
    MedicalAppointmentCreatedEvent.OutputObject
  >;
  getEvent(
    key: "MedicalRecordCreated"
  ): TypedContractEvent<
    MedicalRecordCreatedEvent.InputTuple,
    MedicalRecordCreatedEvent.OutputTuple,
    MedicalRecordCreatedEvent.OutputObject
  >;

  filters: {
    "MedicalAppointmentCreated(uint256,uint256,uint256,string,uint256)": TypedContractEvent<
      MedicalAppointmentCreatedEvent.InputTuple,
      MedicalAppointmentCreatedEvent.OutputTuple,
      MedicalAppointmentCreatedEvent.OutputObject
    >;
    MedicalAppointmentCreated: TypedContractEvent<
      MedicalAppointmentCreatedEvent.InputTuple,
      MedicalAppointmentCreatedEvent.OutputTuple,
      MedicalAppointmentCreatedEvent.OutputObject
    >;

    "MedicalRecordCreated(uint256,string,uint8,uint8,string,string)": TypedContractEvent<
      MedicalRecordCreatedEvent.InputTuple,
      MedicalRecordCreatedEvent.OutputTuple,
      MedicalRecordCreatedEvent.OutputObject
    >;
    MedicalRecordCreated: TypedContractEvent<
      MedicalRecordCreatedEvent.InputTuple,
      MedicalRecordCreatedEvent.OutputTuple,
      MedicalRecordCreatedEvent.OutputObject
    >;
  };
}
