/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export declare namespace VetRegistry {
  export type MedicalAppointmentStruct = {
    petId: BigNumberish;
    date: BigNumberish;
    time: string;
    appointmentValue: BigNumberish;
    paidValue: BigNumberish;
  };

  export type MedicalAppointmentStructOutput = [
    petId: bigint,
    date: bigint,
    time: string,
    appointmentValue: bigint,
    paidValue: bigint
  ] & {
    petId: bigint;
    date: bigint;
    time: string;
    appointmentValue: bigint;
    paidValue: bigint;
  };

  export type MedicalRecordStruct = {
    name: string;
    age: BigNumberish;
    animalType: BigNumberish;
    caretakerName: string;
    caretakerPhone: string;
  };

  export type MedicalRecordStructOutput = [
    name: string,
    age: bigint,
    animalType: bigint,
    caretakerName: string,
    caretakerPhone: string
  ] & {
    name: string;
    age: bigint;
    animalType: bigint;
    caretakerName: string;
    caretakerPhone: string;
  };
}

export interface VetRegistryInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "getAppointment"
      | "getAppointmentCount"
      | "getMedicalRecord"
      | "getPetAppointments"
      | "getPetCount"
      | "owner"
      | "payAppointmentToken"
      | "registerPet"
      | "scheduleAppointment"
      | "withdrawToken"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "AppointmentPaidToken"
      | "MedicalAppointmentCreated"
      | "MedicalRecordCreated"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "getAppointment",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getAppointmentCount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getMedicalRecord",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getPetAppointments",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getPetCount",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "payAppointmentToken",
    values: [BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "registerPet",
    values: [string, BigNumberish, BigNumberish, string, string]
  ): string;
  encodeFunctionData(
    functionFragment: "scheduleAppointment",
    values: [BigNumberish, BigNumberish, string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "withdrawToken",
    values: [AddressLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "getAppointment",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getAppointmentCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getMedicalRecord",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getPetAppointments",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getPetCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "payAppointmentToken",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "registerPet",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "scheduleAppointment",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "withdrawToken",
    data: BytesLike
  ): Result;
}

export namespace AppointmentPaidTokenEvent {
  export type InputTuple = [
    appointmentId: BigNumberish,
    payer: AddressLike,
    token: AddressLike,
    amount: BigNumberish
  ];
  export type OutputTuple = [
    appointmentId: bigint,
    payer: string,
    token: string,
    amount: bigint
  ];
  export interface OutputObject {
    appointmentId: bigint;
    payer: string;
    token: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace MedicalAppointmentCreatedEvent {
  export type InputTuple = [
    id: BigNumberish,
    petId: BigNumberish,
    date: BigNumberish,
    time: string,
    appointmentValue: BigNumberish
  ];
  export type OutputTuple = [
    id: bigint,
    petId: bigint,
    date: bigint,
    time: string,
    appointmentValue: bigint
  ];
  export interface OutputObject {
    id: bigint;
    petId: bigint;
    date: bigint;
    time: string;
    appointmentValue: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace MedicalRecordCreatedEvent {
  export type InputTuple = [
    id: BigNumberish,
    name: string,
    age: BigNumberish,
    animalType: BigNumberish,
    caretakerName: string,
    caretakerPhone: string
  ];
  export type OutputTuple = [
    id: bigint,
    name: string,
    age: bigint,
    animalType: bigint,
    caretakerName: string,
    caretakerPhone: string
  ];
  export interface OutputObject {
    id: bigint;
    name: string;
    age: bigint;
    animalType: bigint;
    caretakerName: string;
    caretakerPhone: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface VetRegistry extends BaseContract {
  connect(runner?: ContractRunner | null): VetRegistry;
  waitForDeployment(): Promise<this>;

  interface: VetRegistryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  getAppointment: TypedContractMethod<
    [id: BigNumberish],
    [VetRegistry.MedicalAppointmentStructOutput],
    "view"
  >;

  getAppointmentCount: TypedContractMethod<[], [bigint], "view">;

  getMedicalRecord: TypedContractMethod<
    [id: BigNumberish],
    [VetRegistry.MedicalRecordStructOutput],
    "view"
  >;

  getPetAppointments: TypedContractMethod<
    [petId: BigNumberish],
    [bigint[]],
    "view"
  >;

  getPetCount: TypedContractMethod<[], [bigint], "view">;

  owner: TypedContractMethod<[], [string], "view">;

  payAppointmentToken: TypedContractMethod<
    [id: BigNumberish, token: AddressLike],
    [void],
    "nonpayable"
  >;

  registerPet: TypedContractMethod<
    [
      name: string,
      age: BigNumberish,
      animalType: BigNumberish,
      caretakerName: string,
      caretakerPhone: string
    ],
    [bigint],
    "nonpayable"
  >;

  scheduleAppointment: TypedContractMethod<
    [
      petId: BigNumberish,
      date: BigNumberish,
      time: string,
      appointmentValue: BigNumberish
    ],
    [bigint],
    "nonpayable"
  >;

  withdrawToken: TypedContractMethod<
    [token: AddressLike],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "getAppointment"
  ): TypedContractMethod<
    [id: BigNumberish],
    [VetRegistry.MedicalAppointmentStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getAppointmentCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getMedicalRecord"
  ): TypedContractMethod<
    [id: BigNumberish],
    [VetRegistry.MedicalRecordStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getPetAppointments"
  ): TypedContractMethod<[petId: BigNumberish], [bigint[]], "view">;
  getFunction(
    nameOrSignature: "getPetCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "payAppointmentToken"
  ): TypedContractMethod<
    [id: BigNumberish, token: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "registerPet"
  ): TypedContractMethod<
    [
      name: string,
      age: BigNumberish,
      animalType: BigNumberish,
      caretakerName: string,
      caretakerPhone: string
    ],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "scheduleAppointment"
  ): TypedContractMethod<
    [
      petId: BigNumberish,
      date: BigNumberish,
      time: string,
      appointmentValue: BigNumberish
    ],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "withdrawToken"
  ): TypedContractMethod<[token: AddressLike], [void], "nonpayable">;

  getEvent(
    key: "AppointmentPaidToken"
  ): TypedContractEvent<
    AppointmentPaidTokenEvent.InputTuple,
    AppointmentPaidTokenEvent.OutputTuple,
    AppointmentPaidTokenEvent.OutputObject
  >;
  getEvent(
    key: "MedicalAppointmentCreated"
  ): TypedContractEvent<
    MedicalAppointmentCreatedEvent.InputTuple,
    MedicalAppointmentCreatedEvent.OutputTuple,
    MedicalAppointmentCreatedEvent.OutputObject
  >;
  getEvent(
    key: "MedicalRecordCreated"
  ): TypedContractEvent<
    MedicalRecordCreatedEvent.InputTuple,
    MedicalRecordCreatedEvent.OutputTuple,
    MedicalRecordCreatedEvent.OutputObject
  >;

  filters: {
    "AppointmentPaidToken(uint256,address,address,uint256)": TypedContractEvent<
      AppointmentPaidTokenEvent.InputTuple,
      AppointmentPaidTokenEvent.OutputTuple,
      AppointmentPaidTokenEvent.OutputObject
    >;
    AppointmentPaidToken: TypedContractEvent<
      AppointmentPaidTokenEvent.InputTuple,
      AppointmentPaidTokenEvent.OutputTuple,
      AppointmentPaidTokenEvent.OutputObject
    >;

    "MedicalAppointmentCreated(uint256,uint256,uint256,string,uint256)": TypedContractEvent<
      MedicalAppointmentCreatedEvent.InputTuple,
      MedicalAppointmentCreatedEvent.OutputTuple,
      MedicalAppointmentCreatedEvent.OutputObject
    >;
    MedicalAppointmentCreated: TypedContractEvent<
      MedicalAppointmentCreatedEvent.InputTuple,
      MedicalAppointmentCreatedEvent.OutputTuple,
      MedicalAppointmentCreatedEvent.OutputObject
    >;

    "MedicalRecordCreated(uint256,string,uint8,uint8,string,string)": TypedContractEvent<
      MedicalRecordCreatedEvent.InputTuple,
      MedicalRecordCreatedEvent.OutputTuple,
      MedicalRecordCreatedEvent.OutputObject
    >;
    MedicalRecordCreated: TypedContractEvent<
      MedicalRecordCreatedEvent.InputTuple,
      MedicalRecordCreatedEvent.OutputTuple,
      MedicalRecordCreatedEvent.OutputObject
    >;
  };
}
